# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm6375-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter hawao,$(TARGET_DEVICE)),)

endif
